export type UkLocation = {
  slug: string;
  /** Value matched against listings.city */
  city: string;
  name: string;
  county: string;
  region: string;
  /** Postcode areas covering the town */
  postcodes: string[];
  intro: string;
  neighbourhoods: string[];
  transport: string[];
  nearby: string[];
};

const CURATED_LOCATIONS: UkLocation[] = [
  {
    slug: "london",
    city: "London",
    name: "London",
    county: "Greater London",
    region: "London",
    postcodes: ["E", "EC", "N", "NW", "SE", "SW", "W", "WC"],
    intro:
      "London's market spans period conversions in the inner boroughs, new-build riverside towers and family housing in the outer commuter belt. Stock moves quickly and pricing varies sharply street by street.",
    neighbourhoods: ["Islington", "Clapham", "Hackney", "Ealing", "Greenwich", "Croydon"],
    transport: ["Underground and Overground network", "Elizabeth line east–west", "Six mainline terminals"],
    nearby: ["croydon", "watford", "romford", "kingston-upon-thames"],
  },
  {
    slug: "manchester",
    city: "Manchester",
    name: "Manchester",
    county: "Greater Manchester",
    region: "North West",
    postcodes: ["M"],
    intro:
      "Manchester combines a dense city-centre apartment market around Ancoats, Deansgate and NOMA with strong suburban demand in Didsbury, Chorlton and Prestwich. Student and professional lettings underpin rental activity.",
    neighbourhoods: ["Ancoats", "Northern Quarter", "Didsbury", "Chorlton", "Salford Quays"],
    transport: ["Metrolink tram network", "Manchester Piccadilly mainline", "Manchester Airport"],
    nearby: ["salford", "stockport", "bolton", "liverpool"],
  },
  {
    slug: "birmingham",
    city: "Birmingham",
    name: "Birmingham",
    county: "West Midlands",
    region: "West Midlands",
    postcodes: ["B"],
    intro:
      "Birmingham's city core is dominated by apartment schemes around the Jewellery Quarter and Digbeth, while Moseley, Harborne and Edgbaston carry the family and professional letting demand.",
    neighbourhoods: ["Jewellery Quarter", "Digbeth", "Harborne", "Moseley", "Edgbaston"],
    transport: ["Birmingham New Street", "West Midlands Metro", "M6 / M42 corridors"],
    nearby: ["solihull", "wolverhampton", "coventry", "walsall"],
  },
  {
    slug: "leeds",
    city: "Leeds",
    name: "Leeds",
    county: "West Yorkshire",
    region: "Yorkshire and the Humber",
    postcodes: ["LS"],
    intro:
      "Leeds pairs a financial and legal employment base with a large student population, giving a deep rental market in Headingley, Hyde Park and the city centre alongside family housing in Roundhay and Horsforth.",
    neighbourhoods: ["Headingley", "Roundhay", "Horsforth", "Chapel Allerton", "City Centre"],
    transport: ["Leeds station", "M1 / M62 junction", "Leeds Bradford Airport"],
    nearby: ["bradford", "wakefield", "harrogate", "york"],
  },
  {
    slug: "liverpool",
    city: "Liverpool",
    name: "Liverpool",
    county: "Merseyside",
    region: "North West",
    postcodes: ["L"],
    intro:
      "Liverpool offers some of the most affordable entry prices of any major English city, with terraced stock across Kensington and Anfield and apartment supply around the waterfront and Baltic Triangle.",
    neighbourhoods: ["Baltic Triangle", "Aigburth", "Woolton", "Waterfront", "Allerton"],
    transport: ["Merseyrail network", "Liverpool Lime Street", "Liverpool John Lennon Airport"],
    nearby: ["wirral", "st-helens", "manchester", "chester"],
  },
  {
    slug: "bristol",
    city: "Bristol",
    name: "Bristol",
    county: "Bristol",
    region: "South West",
    postcodes: ["BS"],
    intro:
      "Bristol has a constrained supply and consistently competitive rental market, with Clifton and Redland at the premium end and Bedminster, Easton and Southville drawing first-time buyers.",
    neighbourhoods: ["Clifton", "Redland", "Southville", "Bedminster", "Easton"],
    transport: ["Bristol Temple Meads", "M4 / M5 interchange", "Bristol Airport"],
    nearby: ["bath", "cardiff", "gloucester", "swindon"],
  },
  {
    slug: "sheffield",
    city: "Sheffield",
    name: "Sheffield",
    county: "South Yorkshire",
    region: "Yorkshire and the Humber",
    postcodes: ["S"],
    intro:
      "Sheffield's two universities support a large shared-house and HMO market around Broomhill and Crookes, while Fulwood, Dore and Nether Edge serve the family end.",
    neighbourhoods: ["Broomhill", "Crookes", "Nether Edge", "Fulwood", "Kelham Island"],
    transport: ["Sheffield station", "Supertram network", "M1 corridor"],
    nearby: ["rotherham", "doncaster", "chesterfield", "barnsley"],
  },
  {
    slug: "nottingham",
    city: "Nottingham",
    name: "Nottingham",
    county: "Nottinghamshire",
    region: "East Midlands",
    postcodes: ["NG"],
    intro:
      "Nottingham has a well-established licensed HMO sector around Lenton and Dunkirk, plus growing city-centre apartment supply and family demand in West Bridgford and Mapperley.",
    neighbourhoods: ["West Bridgford", "Lenton", "Beeston", "Mapperley", "The Park"],
    transport: ["Nottingham station", "NET tram", "M1 junctions 24–26"],
    nearby: ["derby", "leicester", "mansfield", "loughborough"],
  },
  {
    slug: "leicester",
    city: "Leicester",
    name: "Leicester",
    county: "Leicestershire",
    region: "East Midlands",
    postcodes: ["LE"],
    intro:
      "Leicester's market is driven by a diverse rental base and steady owner-occupier demand in Clarendon Park, Stoneygate and Oadby, with conversions concentrated near the two universities.",
    neighbourhoods: ["Clarendon Park", "Stoneygate", "Oadby", "Knighton", "City Centre"],
    transport: ["Leicester station", "M1 / M69", "East Midlands Airport"],
    nearby: ["nottingham", "coventry", "northampton", "derby"],
  },
  {
    slug: "newcastle-upon-tyne",
    city: "Newcastle upon Tyne",
    name: "Newcastle upon Tyne",
    county: "Tyne and Wear",
    region: "North East",
    postcodes: ["NE"],
    intro:
      "Newcastle's Tyneside flats give the city an unusual stock profile, with student and young-professional letting concentrated in Jesmond, Heaton and Ouseburn.",
    neighbourhoods: ["Jesmond", "Heaton", "Gosforth", "Ouseburn", "Quayside"],
    transport: ["Tyne and Wear Metro", "Newcastle Central", "Newcastle Airport"],
    nearby: ["gateshead", "sunderland", "durham", "north-shields"],
  },
  {
    slug: "glasgow",
    city: "Glasgow",
    name: "Glasgow",
    county: "Glasgow City",
    region: "Scotland",
    postcodes: ["G"],
    intro:
      "Glasgow's sandstone tenement flats dominate the West End and Southside. Scottish conveyancing and PRT tenancy rules apply, so timelines and paperwork differ from England and Wales.",
    neighbourhoods: ["West End", "Shawlands", "Dennistoun", "Merchant City", "Pollokshields"],
    transport: ["Glasgow Subway", "Central and Queen Street stations", "Glasgow Airport"],
    nearby: ["paisley", "edinburgh", "east-kilbride", "hamilton"],
  },
  {
    slug: "edinburgh",
    city: "Edinburgh",
    name: "Edinburgh",
    county: "City of Edinburgh",
    region: "Scotland",
    postcodes: ["EH"],
    intro:
      "Edinburgh runs a tight supply market with New Town and Stockbridge at the top end and Leith, Gorgie and Portobello absorbing much of the rental demand. Short-let licensing rules apply across the city.",
    neighbourhoods: ["New Town", "Stockbridge", "Leith", "Morningside", "Portobello"],
    transport: ["Edinburgh Waverley", "Edinburgh Trams", "Edinburgh Airport"],
    nearby: ["glasgow", "livingston", "dunfermline", "musselburgh"],
  },
  {
    slug: "cardiff",
    city: "Cardiff",
    name: "Cardiff",
    county: "Cardiff",
    region: "Wales",
    postcodes: ["CF"],
    intro:
      "Cardiff's rental market centres on Cathays and Roath for students and Pontcanna, Llandaff and Penarth for families. Welsh landlord and agent registration under Rent Smart Wales is mandatory.",
    neighbourhoods: ["Pontcanna", "Roath", "Cathays", "Llandaff", "Cardiff Bay"],
    transport: ["Cardiff Central", "Valley Lines rail", "M4 corridor"],
    nearby: ["newport", "swansea", "bristol", "barry"],
  },
  {
    slug: "swansea",
    city: "Swansea",
    name: "Swansea",
    county: "Swansea",
    region: "Wales",
    postcodes: ["SA"],
    intro:
      "Swansea combines coastal demand around Mumbles and Gower with an affordable city stock and a substantial student letting sector in Uplands and Brynmill.",
    neighbourhoods: ["Mumbles", "Uplands", "Sketty", "Brynmill", "Marina"],
    transport: ["Swansea station", "M4 junctions 42–47", "Coastal bus network"],
    nearby: ["cardiff", "neath", "llanelli", "bridgend"],
  },
  {
    slug: "belfast",
    city: "Belfast",
    name: "Belfast",
    county: "County Antrim",
    region: "Northern Ireland",
    postcodes: ["BT"],
    intro:
      "Belfast has a distinct legal framework for property transactions and tenancies in Northern Ireland, with demand concentrated in South Belfast, Titanic Quarter and the Holylands student area.",
    neighbourhoods: ["South Belfast", "Titanic Quarter", "Stranmillis", "Ballyhackamore", "Malone"],
    transport: ["Belfast Grand Central", "Glider bus rapid transit", "Belfast City Airport"],
    nearby: ["lisburn", "bangor", "newtownabbey", "derry"],
  },
  {
    slug: "brighton",
    city: "Brighton",
    name: "Brighton",
    county: "East Sussex",
    region: "South East",
    postcodes: ["BN"],
    intro:
      "Brighton and Hove has limited supply, high conversion density and a strong professional-commuter base on the London line, keeping both sales and lettings competitive year round.",
    neighbourhoods: ["Hove", "Kemptown", "Preston Park", "Hanover", "Seven Dials"],
    transport: ["Brighton mainline to London Victoria", "Thameslink services", "A23 / M23"],
    nearby: ["worthing", "eastbourne", "crawley", "lewes"],
  },
  {
    slug: "southampton",
    city: "Southampton",
    name: "Southampton",
    county: "Hampshire",
    region: "South East",
    postcodes: ["SO"],
    intro:
      "Southampton's port and university economy supports steady rental turnover in Portswood and Highfield, with waterfront apartments at Ocean Village at the premium end.",
    neighbourhoods: ["Portswood", "Bassett", "Ocean Village", "Shirley", "Bitterne"],
    transport: ["Southampton Central", "M3 / M27", "Southampton Airport"],
    nearby: ["portsmouth", "winchester", "eastleigh", "bournemouth"],
  },
  {
    slug: "portsmouth",
    city: "Portsmouth",
    name: "Portsmouth",
    county: "Hampshire",
    region: "South East",
    postcodes: ["PO"],
    intro:
      "Portsmouth is densely built on Portsea Island, giving a compact terraced and flat market in Southsea and Fratton with naval and university employment behind rental demand.",
    neighbourhoods: ["Southsea", "Old Portsmouth", "Fratton", "Cosham", "Gunwharf"],
    transport: ["Portsmouth Harbour and Portsmouth & Southsea stations", "Isle of Wight ferries", "M275"],
    nearby: ["southampton", "havant", "chichester", "fareham"],
  },
  {
    slug: "reading",
    city: "Reading",
    name: "Reading",
    county: "Berkshire",
    region: "South East",
    postcodes: ["RG"],
    intro:
      "Reading is a core Thames Valley commuter and tech employment centre. Elizabeth line services have widened its catchment, keeping demand firm across Caversham, Earley and the town centre.",
    neighbourhoods: ["Caversham", "Earley", "Tilehurst", "Whitley", "Town Centre"],
    transport: ["Elizabeth line", "Great Western mainline", "M4 junctions 10–12"],
    nearby: ["slough", "bracknell", "basingstoke", "oxford"],
  },
  {
    slug: "oxford",
    city: "Oxford",
    name: "Oxford",
    county: "Oxfordshire",
    region: "South East",
    postcodes: ["OX"],
    intro:
      "Oxford has severe supply constraints from green belt and conservation policy, an exceptionally deep academic rental market and strict HMO licensing across the city.",
    neighbourhoods: ["Jericho", "Headington", "Summertown", "Cowley", "Iffley"],
    transport: ["Oxford and Oxford Parkway stations", "A34 / M40", "Park and ride network"],
    nearby: ["reading", "banbury", "bicester", "abingdon"],
  },
  {
    slug: "cambridge",
    city: "Cambridge",
    name: "Cambridge",
    county: "Cambridgeshire",
    region: "East of England",
    postcodes: ["CB"],
    intro:
      "Cambridge's life sciences and technology cluster keeps rental demand high year round, with new-build supply at Eddington and Trumpington and period stock in Newnham and Petersfield.",
    neighbourhoods: ["Newnham", "Trumpington", "Chesterton", "Petersfield", "Eddington"],
    transport: ["Cambridge and Cambridge North stations", "Guided busway", "M11 corridor"],
    nearby: ["peterborough", "ely", "st-neots", "bishops-stortford"],
  },
  {
    slug: "milton-keynes",
    city: "Milton Keynes",
    name: "Milton Keynes",
    county: "Buckinghamshire",
    region: "South East",
    postcodes: ["MK"],
    intro:
      "Milton Keynes offers modern grid-plan housing, plentiful new-build supply and fast West Coast mainline access, making it a common relocation target for London commuters.",
    neighbourhoods: ["Central Milton Keynes", "Wolverton", "Newport Pagnell", "Bletchley", "Woburn Sands"],
    transport: ["Milton Keynes Central", "M1 junctions 13–14", "Redway cycle network"],
    nearby: ["northampton", "luton", "bedford", "aylesbury"],
  },
  {
    slug: "coventry",
    city: "Coventry",
    name: "Coventry",
    county: "West Midlands",
    region: "West Midlands",
    postcodes: ["CV"],
    intro:
      "Coventry's two universities and automotive engineering base underpin a broad rental market, with Earlsdon and Cheylesmore popular for families and city-centre blocks aimed at students.",
    neighbourhoods: ["Earlsdon", "Cheylesmore", "Canley", "Stoke", "City Centre"],
    transport: ["Coventry station", "M6 / M69 / M40", "Birmingham Airport"],
    nearby: ["birmingham", "leamington-spa", "rugby", "nuneaton"],
  },
  {
    slug: "stoke-on-trent",
    city: "Stoke-on-Trent",
    name: "Stoke-on-Trent",
    county: "Staffordshire",
    region: "West Midlands",
    postcodes: ["ST"],
    intro:
      "Stoke-on-Trent remains one of England's lowest-priced urban markets, drawing yield-focused investors to terraced stock across the six towns.",
    neighbourhoods: ["Hanley", "Trentham", "Newcastle-under-Lyme", "Burslem", "Longton"],
    transport: ["Stoke-on-Trent station", "A500 / M6", "West Coast mainline"],
    nearby: ["crewe", "stafford", "macclesfield", "derby"],
  },
  {
    slug: "derby",
    city: "Derby",
    name: "Derby",
    county: "Derbyshire",
    region: "East Midlands",
    postcodes: ["DE"],
    intro:
      "Derby's rail and aerospace employers support stable rental demand, with Littleover, Mickleover and Allestree favoured by families and city-centre flats serving young professionals.",
    neighbourhoods: ["Littleover", "Mickleover", "Allestree", "Darley Abbey", "City Centre"],
    transport: ["Derby station", "A38 / A52", "East Midlands Airport"],
    nearby: ["nottingham", "burton-upon-trent", "chesterfield", "leicester"],
  },
  {
    slug: "hull",
    city: "Hull",
    name: "Hull",
    county: "East Riding of Yorkshire",
    region: "Yorkshire and the Humber",
    postcodes: ["HU"],
    intro:
      "Hull's low entry prices and renewable-energy employment base attract investors, with Avenues and Newland popular for lettings and Kingswood for newer family housing.",
    neighbourhoods: ["The Avenues", "Newland", "Kingswood", "Old Town", "Cottingham"],
    transport: ["Hull Paragon Interchange", "M62 corridor", "Port of Hull ferries"],
    nearby: ["beverley", "grimsby", "york", "scunthorpe"],
  },
  {
    slug: "york",
    city: "York",
    name: "York",
    county: "North Yorkshire",
    region: "Yorkshire and the Humber",
    postcodes: ["YO"],
    intro:
      "York's conservation-heavy centre limits new supply, and tourism, rail and university employment keep both sales and lettings tightly competitive.",
    neighbourhoods: ["Bishopthorpe Road", "Fulford", "Clifton", "Heworth", "Acomb"],
    transport: ["York station on the East Coast mainline", "A64 to Leeds", "Park and ride network"],
    nearby: ["leeds", "harrogate", "selby", "hull"],
  },
  {
    slug: "harrogate",
    city: "Harrogate",
    name: "Harrogate",
    county: "North Yorkshire",
    region: "Yorkshire and the Humber",
    postcodes: ["HG"],
    intro:
      "Harrogate is a premium North Yorkshire spa town with strong family demand, period villas around the Duchy estate and a limited flow of new stock.",
    neighbourhoods: ["Duchy", "Pannal", "Starbeck", "Knaresborough", "Bilton"],
    transport: ["Harrogate line to Leeds and York", "A1(M) access", "Leeds Bradford Airport"],
    nearby: ["leeds", "york", "ripon", "wetherby"],
  },
  {
    slug: "bath",
    city: "Bath",
    name: "Bath",
    county: "Somerset",
    region: "South West",
    postcodes: ["BA"],
    intro:
      "Bath's World Heritage status and Georgian terraces produce a supply-restricted premium market, with two universities adding sustained rental demand.",
    neighbourhoods: ["Widcombe", "Bathwick", "Lansdown", "Oldfield Park", "Weston"],
    transport: ["Bath Spa station", "A4 / M4 junction 18", "Bristol Airport"],
    nearby: ["bristol", "trowbridge", "chippenham", "frome"],
  },
  {
    slug: "exeter",
    city: "Exeter",
    name: "Exeter",
    county: "Devon",
    region: "South West",
    postcodes: ["EX"],
    intro:
      "Exeter is the South West's regional service centre, with university-driven lettings in St James and Pennsylvania and family demand in Topsham and Exwick.",
    neighbourhoods: ["St Leonard's", "Topsham", "Pennsylvania", "Exwick", "Heavitree"],
    transport: ["Exeter St Davids and Central", "M5 junctions 29–31", "Exeter Airport"],
    nearby: ["plymouth", "torquay", "taunton", "newton-abbot"],
  },
  {
    slug: "plymouth",
    city: "Plymouth",
    name: "Plymouth",
    county: "Devon",
    region: "South West",
    postcodes: ["PL"],
    intro:
      "Plymouth's naval and marine sector plus a large university keep rental demand steady, with waterfront stock in the Hoe and Barbican and family housing in Plympton and Plymstock.",
    neighbourhoods: ["The Hoe", "Barbican", "Plympton", "Plymstock", "Mutley"],
    transport: ["Plymouth station", "A38 Devon Expressway", "Brittany Ferries port"],
    nearby: ["exeter", "torquay", "saltash", "tavistock"],
  },
  {
    slug: "bournemouth",
    city: "Bournemouth",
    name: "Bournemouth",
    county: "Dorset",
    region: "South West",
    postcodes: ["BH"],
    intro:
      "Bournemouth's coastal position drives holiday-let and student demand alongside a conventional residential market, with Westbourne and Southbourne the strongest sub-areas.",
    neighbourhoods: ["Westbourne", "Southbourne", "Winton", "Charminster", "Boscombe"],
    transport: ["Bournemouth station to London Waterloo", "A31 / M27", "Bournemouth Airport"],
    nearby: ["poole", "christchurch", "southampton", "salisbury"],
  },
  {
    slug: "norwich",
    city: "Norwich",
    name: "Norwich",
    county: "Norfolk",
    region: "East of England",
    postcodes: ["NR"],
    intro:
      "Norwich anchors the East Anglian market with a compact medieval core, university lettings in the Golden Triangle and steady demand from Norfolk relocations.",
    neighbourhoods: ["Golden Triangle", "Thorpe St Andrew", "Eaton", "Norwich Over the Water", "Sprowston"],
    transport: ["Norwich station to London Liverpool Street", "A11 / A47", "Norwich Airport"],
    nearby: ["great-yarmouth", "ipswich", "cambridge", "kings-lynn"],
  },
  {
    slug: "ipswich",
    city: "Ipswich",
    name: "Ipswich",
    county: "Suffolk",
    region: "East of England",
    postcodes: ["IP"],
    intro:
      "Ipswich offers relatively affordable Suffolk pricing with waterfront apartment stock and commuter access to London Liverpool Street in around an hour.",
    neighbourhoods: ["Waterfront", "Christchurch Park", "Kesgrave", "Rushmere", "Martlesham"],
    transport: ["Ipswich station", "A12 / A14", "Port of Felixstowe nearby"],
    nearby: ["colchester", "norwich", "felixstowe", "bury-st-edmunds"],
  },
  {
    slug: "luton",
    city: "Luton",
    name: "Luton",
    county: "Bedfordshire",
    region: "East of England",
    postcodes: ["LU"],
    intro:
      "Luton attracts buyers priced out of north London, with Thameslink services into St Pancras and airport-related employment supporting rental demand.",
    neighbourhoods: ["Stopsley", "Bushmead", "Leagrave", "High Town", "Dunstable"],
    transport: ["Thameslink to London St Pancras", "London Luton Airport", "M1 junctions 10–11"],
    nearby: ["milton-keynes", "st-albans", "bedford", "watford"],
  },
  {
    slug: "watford",
    city: "Watford",
    name: "Watford",
    county: "Hertfordshire",
    region: "East of England",
    postcodes: ["WD"],
    intro:
      "Watford is a Hertfordshire commuter hub with Metropolitan line and West Coast mainline access, mixing Victorian terraces with substantial new apartment supply.",
    neighbourhoods: ["Cassiobury", "Nascot Wood", "Oxhey", "Garston", "Croxley Green"],
    transport: ["Watford Junction", "Metropolitan line", "M1 / M25 junction"],
    nearby: ["st-albans", "luton", "london", "hemel-hempstead"],
  },
  {
    slug: "st-albans",
    city: "St Albans",
    name: "St Albans",
    county: "Hertfordshire",
    region: "East of England",
    postcodes: ["AL"],
    intro:
      "St Albans is a high-value commuter city with strong school catchments, conservation-area period stock and fast Thameslink services into central London.",
    neighbourhoods: ["Fleetville", "Marshalswick", "St Stephens", "Verulam", "Harpenden"],
    transport: ["Thameslink to St Pancras in ~20 minutes", "M25 junction 21A", "A1(M) access"],
    nearby: ["watford", "luton", "hemel-hempstead", "london"],
  },
  {
    slug: "croydon",
    city: "Croydon",
    name: "Croydon",
    county: "Greater London",
    region: "London",
    postcodes: ["CR"],
    intro:
      "Croydon has seen large-scale tall-building regeneration around East Croydon alongside established suburban housing in Purley, Shirley and Sanderstead.",
    neighbourhoods: ["East Croydon", "Purley", "Shirley", "South Norwood", "Sanderstead"],
    transport: ["East Croydon to London Bridge and Victoria", "Tramlink network", "Gatwick in ~15 minutes"],
    nearby: ["london", "bromley", "sutton", "crawley"],
  },
  {
    slug: "slough",
    city: "Slough",
    name: "Slough",
    county: "Berkshire",
    region: "South East",
    postcodes: ["SL"],
    intro:
      "Slough sits on the Elizabeth line with a major trading estate employment base, giving a busy rental market and steady investor interest.",
    neighbourhoods: ["Langley", "Cippenham", "Upton Park", "Chalvey", "Burnham"],
    transport: ["Elizabeth line to central London", "M4 junctions 5–7", "Heathrow nearby"],
    nearby: ["reading", "windsor", "uxbridge", "maidenhead"],
  },
  {
    slug: "stockport",
    city: "Stockport",
    name: "Stockport",
    county: "Greater Manchester",
    region: "North West",
    postcodes: ["SK"],
    intro:
      "Stockport has become one of Greater Manchester's fastest-changing markets, with town-centre regeneration and established demand in Heaton Moor, Bramhall and Marple.",
    neighbourhoods: ["Heaton Moor", "Bramhall", "Marple", "Cheadle Hulme", "Reddish"],
    transport: ["Stockport station on the West Coast mainline", "M60 junctions 1–3", "Manchester Airport"],
    nearby: ["manchester", "macclesfield", "salford", "bolton"],
  },
  {
    slug: "salford",
    city: "Salford",
    name: "Salford",
    county: "Greater Manchester",
    region: "North West",
    postcodes: ["M"],
    intro:
      "Salford's MediaCityUK and Quays regeneration created a large modern apartment market, with more traditional terraced stock in Eccles, Swinton and Worsley.",
    neighbourhoods: ["Salford Quays", "MediaCityUK", "Eccles", "Worsley", "Swinton"],
    transport: ["Metrolink Eccles and MediaCity lines", "M60 / M602", "Salford Central station"],
    nearby: ["manchester", "bolton", "stockport", "wigan"],
  },
  {
    slug: "bolton",
    city: "Bolton",
    name: "Bolton",
    county: "Greater Manchester",
    region: "North West",
    postcodes: ["BL"],
    intro:
      "Bolton pairs affordable terraced stock with sought-after villages such as Bromley Cross and Lostock, and offers direct rail access into Manchester.",
    neighbourhoods: ["Bromley Cross", "Lostock", "Horwich", "Farnworth", "Westhoughton"],
    transport: ["Bolton station to Manchester", "M61 corridor", "Metrolink connections via Manchester"],
    nearby: ["salford", "manchester", "wigan", "bury"],
  },
  {
    slug: "preston",
    city: "Preston",
    name: "Preston",
    county: "Lancashire",
    region: "North West",
    postcodes: ["PR"],
    intro:
      "Preston is Lancashire's administrative centre, with university lettings near the city core and family demand in Fulwood, Penwortham and Longridge.",
    neighbourhoods: ["Fulwood", "Penwortham", "Ashton-on-Ribble", "Longridge", "Ribbleton"],
    transport: ["Preston station on the West Coast mainline", "M6 / M55 / M65", "Manchester Airport"],
    nearby: ["blackpool", "blackburn", "chorley", "lancaster"],
  },
  {
    slug: "chester",
    city: "Chester",
    name: "Chester",
    county: "Cheshire",
    region: "North West",
    postcodes: ["CH"],
    intro:
      "Chester's walled historic centre and Cheshire villages make it a premium regional market, with additional demand from cross-border North Wales commuters.",
    neighbourhoods: ["Handbridge", "Hoole", "Boughton", "Upton", "Christleton"],
    transport: ["Chester station", "A55 North Wales Expressway", "M53 to Liverpool"],
    nearby: ["liverpool", "wrexham", "ellesmere-port", "warrington"],
  },
  {
    slug: "wolverhampton",
    city: "Wolverhampton",
    name: "Wolverhampton",
    county: "West Midlands",
    region: "West Midlands",
    postcodes: ["WV"],
    intro:
      "Wolverhampton offers among the lowest prices in the West Midlands conurbation, with Tettenhall and Penn at the premium end and strong yields elsewhere.",
    neighbourhoods: ["Tettenhall", "Penn", "Wightwick", "Bilston", "Whitmore Reans"],
    transport: ["Wolverhampton station", "West Midlands Metro extension", "M6 / M54"],
    nearby: ["birmingham", "walsall", "telford", "dudley"],
  },
  {
    slug: "northampton",
    city: "Northampton",
    name: "Northampton",
    county: "Northamptonshire",
    region: "East Midlands",
    postcodes: ["NN"],
    intro:
      "Northampton's logistics economy and M1 position support a broad rental market, with Abington and Duston popular locally and new estates expanding the edges.",
    neighbourhoods: ["Abington", "Duston", "Kingsthorpe", "Far Cotton", "Wootton"],
    transport: ["Northampton station to London Euston", "M1 junctions 15–16", "A45 corridor"],
    nearby: ["milton-keynes", "leicester", "bedford", "rugby"],
  },
  {
    slug: "peterborough",
    city: "Peterborough",
    name: "Peterborough",
    county: "Cambridgeshire",
    region: "East of England",
    postcodes: ["PE"],
    intro:
      "Peterborough delivers East Coast mainline access to London at well below Cambridge pricing, with substantial new-build supply around Hampton and Cardea.",
    neighbourhoods: ["Hampton", "Werrington", "Orton", "Longthorpe", "Stanground"],
    transport: ["Peterborough station to King's Cross in ~50 minutes", "A1(M)", "A47 corridor"],
    nearby: ["cambridge", "huntingdon", "stamford", "wisbech"],
  },
  {
    slug: "aberdeen",
    city: "Aberdeen",
    name: "Aberdeen",
    county: "Aberdeen City",
    region: "Scotland",
    postcodes: ["AB"],
    intro:
      "Aberdeen's granite tenements and energy-sector employment give it a cyclical market, with corporate lettings concentrated in the West End and Cults.",
    neighbourhoods: ["West End", "Cults", "Bridge of Don", "Rosemount", "Bieldside"],
    transport: ["Aberdeen station", "Aberdeen International Airport", "AWPR bypass"],
    nearby: ["dundee", "inverness", "stonehaven", "edinburgh"],
  },
];

export function findLocation(slug: string): UkLocation | null {
  return LOCATIONS.find((l) => l.slug === slug) ?? null;
}

export const LOCATIONS_BY_REGION = LOCATIONS.reduce<Record<string, UkLocation[]>>((acc, l) => {
  (acc[l.region] ??= []).push(l);
  return acc;
}, {});
