/**
 * Compact dataset of UK towns and cities used to generate location landing pages.
 * Tuple order: [name, county, region, postcode area]
 * Curated entries in locations.ts take precedence over anything repeated here.
 */
export type TownTuple = [name: string, county: string, region: string, postcode: string];

export const UK_TOWNS: TownTuple[] = [
  // London & Greater London
  ["Croydon", "Greater London", "London", "CR"],
  ["Bromley", "Greater London", "London", "BR"],
  ["Romford", "Greater London", "London", "RM"],
  ["Ilford", "Greater London", "London", "IG"],
  ["Enfield", "Greater London", "London", "EN"],
  ["Harrow", "Greater London", "London", "HA"],
  ["Uxbridge", "Greater London", "London", "UB"],
  ["Twickenham", "Greater London", "London", "TW"],
  ["Kingston upon Thames", "Greater London", "London", "KT"],
  ["Sutton", "Greater London", "London", "SM"],
  ["Wembley", "Greater London", "London", "HA"],
  ["Barking", "Greater London", "London", "IG"],
  ["Hounslow", "Greater London", "London", "TW"],
  ["Ealing", "Greater London", "London", "W"],
  ["Woolwich", "Greater London", "London", "SE"],

  // South East
  ["Slough", "Berkshire", "South East", "SL"],
  ["Windsor", "Berkshire", "South East", "SL"],
  ["Maidenhead", "Berkshire", "South East", "SL"],
  ["Bracknell", "Berkshire", "South East", "RG"],
  ["Newbury", "Berkshire", "South East", "RG"],
  ["Wokingham", "Berkshire", "South East", "RG"],
  ["Basingstoke", "Hampshire", "South East", "RG"],
  ["Winchester", "Hampshire", "South East", "SO"],
  ["Eastleigh", "Hampshire", "South East", "SO"],
  ["Fareham", "Hampshire", "South East", "PO"],
  ["Gosport", "Hampshire", "South East", "PO"],
  ["Havant", "Hampshire", "South East", "PO"],
  ["Andover", "Hampshire", "South East", "SP"],
  ["Aldershot", "Hampshire", "South East", "GU"],
  ["Farnborough", "Hampshire", "South East", "GU"],
  ["Guildford", "Surrey", "South East", "GU"],
  ["Woking", "Surrey", "South East", "GU"],
  ["Camberley", "Surrey", "South East", "GU"],
  ["Epsom", "Surrey", "South East", "KT"],
  ["Redhill", "Surrey", "South East", "RH"],
  ["Reigate", "Surrey", "South East", "RH"],
  ["Staines-upon-Thames", "Surrey", "South East", "TW"],
  ["Crawley", "West Sussex", "South East", "RH"],
  ["Horsham", "West Sussex", "South East", "RH"],
  ["Worthing", "West Sussex", "South East", "BN"],
  ["Chichester", "West Sussex", "South East", "PO"],
  ["Bognor Regis", "West Sussex", "South East", "PO"],
  ["Littlehampton", "West Sussex", "South East", "BN"],
  ["Eastbourne", "East Sussex", "South East", "BN"],
  ["Hastings", "East Sussex", "South East", "TN"],
  ["Lewes", "East Sussex", "South East", "BN"],
  ["Bexhill-on-Sea", "East Sussex", "South East", "TN"],
  ["Maidstone", "Kent", "South East", "ME"],
  ["Canterbury", "Kent", "South East", "CT"],
  ["Dover", "Kent", "South East", "CT"],
  ["Folkestone", "Kent", "South East", "CT"],
  ["Margate", "Kent", "South East", "CT"],
  ["Ramsgate", "Kent", "South East", "CT"],
  ["Ashford", "Kent", "South East", "TN"],
  ["Tunbridge Wells", "Kent", "South East", "TN"],
  ["Tonbridge", "Kent", "South East", "TN"],
  ["Gravesend", "Kent", "South East", "DA"],
  ["Dartford", "Kent", "South East", "DA"],
  ["Chatham", "Kent", "South East", "ME"],
  ["Gillingham", "Kent", "South East", "ME"],
  ["Rochester", "Kent", "South East", "ME"],
  ["Sittingbourne", "Kent", "South East", "ME"],
  ["Oxford", "Oxfordshire", "South East", "OX"],
  ["Banbury", "Oxfordshire", "South East", "OX"],
  ["Bicester", "Oxfordshire", "South East", "OX"],
  ["Abingdon", "Oxfordshire", "South East", "OX"],
  ["Didcot", "Oxfordshire", "South East", "OX"],
  ["High Wycombe", "Buckinghamshire", "South East", "HP"],
  ["Aylesbury", "Buckinghamshire", "South East", "HP"],
  ["Amersham", "Buckinghamshire", "South East", "HP"],
  ["Milton Keynes", "Buckinghamshire", "South East", "MK"],

  // South West
  ["Bath", "Somerset", "South West", "BA"],
  ["Taunton", "Somerset", "South West", "TA"],
  ["Yeovil", "Somerset", "South West", "BA"],
  ["Bridgwater", "Somerset", "South West", "TA"],
  ["Weston-super-Mare", "Somerset", "South West", "BS"],
  ["Exeter", "Devon", "South West", "EX"],
  ["Plymouth", "Devon", "South West", "PL"],
  ["Torquay", "Devon", "South West", "TQ"],
  ["Paignton", "Devon", "South West", "TQ"],
  ["Barnstaple", "Devon", "South West", "EX"],
  ["Newton Abbot", "Devon", "South West", "TQ"],
  ["Exmouth", "Devon", "South West", "EX"],
  ["Truro", "Cornwall", "South West", "TR"],
  ["Falmouth", "Cornwall", "South West", "TR"],
  ["Newquay", "Cornwall", "South West", "TR"],
  ["St Austell", "Cornwall", "South West", "PL"],
  ["Penzance", "Cornwall", "South West", "TR"],
  ["Camborne", "Cornwall", "South West", "TR"],
  ["Bournemouth", "Dorset", "South West", "BH"],
  ["Poole", "Dorset", "South West", "BH"],
  ["Christchurch", "Dorset", "South West", "BH"],
  ["Weymouth", "Dorset", "South West", "DT"],
  ["Dorchester", "Dorset", "South West", "DT"],
  ["Salisbury", "Wiltshire", "South West", "SP"],
  ["Swindon", "Wiltshire", "South West", "SN"],
  ["Chippenham", "Wiltshire", "South West", "SN"],
  ["Trowbridge", "Wiltshire", "South West", "BA"],
  ["Gloucester", "Gloucestershire", "South West", "GL"],
  ["Cheltenham", "Gloucestershire", "South West", "GL"],
  ["Stroud", "Gloucestershire", "South West", "GL"],

  // East of England
  ["Cambridge", "Cambridgeshire", "East of England", "CB"],
  ["Huntingdon", "Cambridgeshire", "East of England", "PE"],
  ["Wisbech", "Cambridgeshire", "East of England", "PE"],
  ["Ely", "Cambridgeshire", "East of England", "CB"],
  ["Norwich", "Norfolk", "East of England", "NR"],
  ["Great Yarmouth", "Norfolk", "East of England", "NR"],
  ["King's Lynn", "Norfolk", "East of England", "PE"],
  ["Thetford", "Norfolk", "East of England", "IP"],
  ["Ipswich", "Suffolk", "East of England", "IP"],
  ["Bury St Edmunds", "Suffolk", "East of England", "IP"],
  ["Lowestoft", "Suffolk", "East of England", "NR"],
  ["Felixstowe", "Suffolk", "East of England", "IP"],
  ["Colchester", "Essex", "East of England", "CO"],
  ["Chelmsford", "Essex", "East of England", "CM"],
  ["Basildon", "Essex", "East of England", "SS"],
  ["Southend-on-Sea", "Essex", "East of England", "SS"],
  ["Harlow", "Essex", "East of England", "CM"],
  ["Braintree", "Essex", "East of England", "CM"],
  ["Clacton-on-Sea", "Essex", "East of England", "CO"],
  ["Grays", "Essex", "East of England", "RM"],
  ["Luton", "Bedfordshire", "East of England", "LU"],
  ["Bedford", "Bedfordshire", "East of England", "MK"],
  ["Dunstable", "Bedfordshire", "East of England", "LU"],
  ["Watford", "Hertfordshire", "East of England", "WD"],
  ["St Albans", "Hertfordshire", "East of England", "AL"],
  ["Hemel Hempstead", "Hertfordshire", "East of England", "HP"],
  ["Stevenage", "Hertfordshire", "East of England", "SG"],
  ["Hertford", "Hertfordshire", "East of England", "SG"],
  ["Welwyn Garden City", "Hertfordshire", "East of England", "AL"],
  ["Hitchin", "Hertfordshire", "East of England", "SG"],
  ["Bishop's Stortford", "Hertfordshire", "East of England", "CM"],

  // West Midlands
  ["Coventry", "West Midlands", "West Midlands", "CV"],
  ["Wolverhampton", "West Midlands", "West Midlands", "WV"],
  ["Solihull", "West Midlands", "West Midlands", "B"],
  ["Walsall", "West Midlands", "West Midlands", "WS"],
  ["Dudley", "West Midlands", "West Midlands", "DY"],
  ["West Bromwich", "West Midlands", "West Midlands", "B"],
  ["Sutton Coldfield", "West Midlands", "West Midlands", "B"],
  ["Stourbridge", "West Midlands", "West Midlands", "DY"],
  ["Halesowen", "West Midlands", "West Midlands", "B"],
  ["Nuneaton", "Warwickshire", "West Midlands", "CV"],
  ["Rugby", "Warwickshire", "West Midlands", "CV"],
  ["Leamington Spa", "Warwickshire", "West Midlands", "CV"],
  ["Warwick", "Warwickshire", "West Midlands", "CV"],
  ["Stratford-upon-Avon", "Warwickshire", "West Midlands", "CV"],
  ["Stoke-on-Trent", "Staffordshire", "West Midlands", "ST"],
  ["Stafford", "Staffordshire", "West Midlands", "ST"],
  ["Burton upon Trent", "Staffordshire", "West Midlands", "DE"],
  ["Tamworth", "Staffordshire", "West Midlands", "B"],
  ["Lichfield", "Staffordshire", "West Midlands", "WS"],
  ["Cannock", "Staffordshire", "West Midlands", "WS"],
  ["Newcastle-under-Lyme", "Staffordshire", "West Midlands", "ST"],
  ["Worcester", "Worcestershire", "West Midlands", "WR"],
  ["Redditch", "Worcestershire", "West Midlands", "B"],
  ["Kidderminster", "Worcestershire", "West Midlands", "DY"],
  ["Bromsgrove", "Worcestershire", "West Midlands", "B"],
  ["Hereford", "Herefordshire", "West Midlands", "HR"],
  ["Shrewsbury", "Shropshire", "West Midlands", "SY"],
  ["Telford", "Shropshire", "West Midlands", "TF"],

  // East Midlands
  ["Derby", "Derbyshire", "East Midlands", "DE"],
  ["Chesterfield", "Derbyshire", "East Midlands", "S"],
  ["Ilkeston", "Derbyshire", "East Midlands", "DE"],
  ["Buxton", "Derbyshire", "East Midlands", "SK"],
  ["Glossop", "Derbyshire", "East Midlands", "SK"],
  ["Mansfield", "Nottinghamshire", "East Midlands", "NG"],
  ["Newark-on-Trent", "Nottinghamshire", "East Midlands", "NG"],
  ["Worksop", "Nottinghamshire", "East Midlands", "S"],
  ["Loughborough", "Leicestershire", "East Midlands", "LE"],
  ["Hinckley", "Leicestershire", "East Midlands", "LE"],
  ["Coalville", "Leicestershire", "East Midlands", "LE"],
  ["Melton Mowbray", "Leicestershire", "East Midlands", "LE"],
  ["Lincoln", "Lincolnshire", "East Midlands", "LN"],
  ["Grimsby", "Lincolnshire", "East Midlands", "DN"],
  ["Scunthorpe", "Lincolnshire", "East Midlands", "DN"],
  ["Boston", "Lincolnshire", "East Midlands", "PE"],
  ["Grantham", "Lincolnshire", "East Midlands", "NG"],
  ["Skegness", "Lincolnshire", "East Midlands", "PE"],
  ["Kettering", "Northamptonshire", "East Midlands", "NN"],
  ["Corby", "Northamptonshire", "East Midlands", "NN"],
  ["Wellingborough", "Northamptonshire", "East Midlands", "NN"],
  ["Rushden", "Northamptonshire", "East Midlands", "NN"],

  // Yorkshire and the Humber
  ["York", "North Yorkshire", "Yorkshire and the Humber", "YO"],
  ["Harrogate", "North Yorkshire", "Yorkshire and the Humber", "HG"],
  ["Scarborough", "North Yorkshire", "Yorkshire and the Humber", "YO"],
  ["Northallerton", "North Yorkshire", "Yorkshire and the Humber", "DL"],
  ["Skipton", "North Yorkshire", "Yorkshire and the Humber", "BD"],
  ["Selby", "North Yorkshire", "Yorkshire and the Humber", "YO"],
  ["Bradford", "West Yorkshire", "Yorkshire and the Humber", "BD"],
  ["Wakefield", "West Yorkshire", "Yorkshire and the Humber", "WF"],
  ["Huddersfield", "West Yorkshire", "Yorkshire and the Humber", "HD"],
  ["Halifax", "West Yorkshire", "Yorkshire and the Humber", "HX"],
  ["Dewsbury", "West Yorkshire", "Yorkshire and the Humber", "WF"],
  ["Keighley", "West Yorkshire", "Yorkshire and the Humber", "BD"],
  ["Castleford", "West Yorkshire", "Yorkshire and the Humber", "WF"],
  ["Pontefract", "West Yorkshire", "Yorkshire and the Humber", "WF"],
  ["Batley", "West Yorkshire", "Yorkshire and the Humber", "WF"],
  ["Barnsley", "South Yorkshire", "Yorkshire and the Humber", "S"],
  ["Doncaster", "South Yorkshire", "Yorkshire and the Humber", "DN"],
  ["Rotherham", "South Yorkshire", "Yorkshire and the Humber", "S"],
  ["Hull", "East Riding of Yorkshire", "Yorkshire and the Humber", "HU"],
  ["Beverley", "East Riding of Yorkshire", "Yorkshire and the Humber", "HU"],
  ["Bridlington", "East Riding of Yorkshire", "Yorkshire and the Humber", "YO"],
  ["Goole", "East Riding of Yorkshire", "Yorkshire and the Humber", "DN"],

  // North West
  ["Salford", "Greater Manchester", "North West", "M"],
  ["Bolton", "Greater Manchester", "North West", "BL"],
  ["Stockport", "Greater Manchester", "North West", "SK"],
  ["Oldham", "Greater Manchester", "North West", "OL"],
  ["Rochdale", "Greater Manchester", "North West", "OL"],
  ["Bury", "Greater Manchester", "North West", "BL"],
  ["Wigan", "Greater Manchester", "North West", "WN"],
  ["Altrincham", "Greater Manchester", "North West", "WA"],
  ["Sale", "Greater Manchester", "North West", "M"],
  ["Ashton-under-Lyne", "Greater Manchester", "North West", "OL"],
  ["Warrington", "Cheshire", "North West", "WA"],
  ["Chester", "Cheshire", "North West", "CH"],
  ["Crewe", "Cheshire", "North West", "CW"],
  ["Macclesfield", "Cheshire", "North West", "SK"],
  ["Northwich", "Cheshire", "North West", "CW"],
  ["Runcorn", "Cheshire", "North West", "WA"],
  ["Widnes", "Cheshire", "North West", "WA"],
  ["Ellesmere Port", "Cheshire", "North West", "CH"],
  ["Birkenhead", "Merseyside", "North West", "CH"],
  ["Wallasey", "Merseyside", "North West", "CH"],
  ["St Helens", "Merseyside", "North West", "WA"],
  ["Southport", "Merseyside", "North West", "PR"],
  ["Bootle", "Merseyside", "North West", "L"],
  ["Preston", "Lancashire", "North West", "PR"],
  ["Blackpool", "Lancashire", "North West", "FY"],
  ["Blackburn", "Lancashire", "North West", "BB"],
  ["Burnley", "Lancashire", "North West", "BB"],
  ["Lancaster", "Lancashire", "North West", "LA"],
  ["Chorley", "Lancashire", "North West", "PR"],
  ["Accrington", "Lancashire", "North West", "BB"],
  ["Skelmersdale", "Lancashire", "North West", "WN"],
  ["Morecambe", "Lancashire", "North West", "LA"],
  ["Carlisle", "Cumbria", "North West", "CA"],
  ["Barrow-in-Furness", "Cumbria", "North West", "LA"],
  ["Kendal", "Cumbria", "North West", "LA"],
  ["Workington", "Cumbria", "North West", "CA"],
  ["Whitehaven", "Cumbria", "North West", "CA"],

  // North East
  ["Sunderland", "Tyne and Wear", "North East", "SR"],
  ["Gateshead", "Tyne and Wear", "North East", "NE"],
  ["South Shields", "Tyne and Wear", "North East", "NE"],
  ["North Shields", "Tyne and Wear", "North East", "NE"],
  ["Washington", "Tyne and Wear", "North East", "NE"],
  ["Durham", "County Durham", "North East", "DH"],
  ["Darlington", "County Durham", "North East", "DL"],
  ["Hartlepool", "County Durham", "North East", "TS"],
  ["Bishop Auckland", "County Durham", "North East", "DL"],
  ["Middlesbrough", "North Yorkshire", "North East", "TS"],
  ["Stockton-on-Tees", "County Durham", "North East", "TS"],
  ["Redcar", "North Yorkshire", "North East", "TS"],
  ["Blyth", "Northumberland", "North East", "NE"],
  ["Ashington", "Northumberland", "North East", "NE"],
  ["Hexham", "Northumberland", "North East", "NE"],
  ["Berwick-upon-Tweed", "Northumberland", "North East", "TD"],

  // Wales
  ["Newport", "Newport", "Wales", "NP"],
  ["Wrexham", "Wrexham", "Wales", "LL"],
  ["Barry", "Vale of Glamorgan", "Wales", "CF"],
  ["Neath", "Neath Port Talbot", "Wales", "SA"],
  ["Port Talbot", "Neath Port Talbot", "Wales", "SA"],
  ["Bridgend", "Bridgend", "Wales", "CF"],
  ["Llanelli", "Carmarthenshire", "Wales", "SA"],
  ["Carmarthen", "Carmarthenshire", "Wales", "SA"],
  ["Merthyr Tydfil", "Merthyr Tydfil", "Wales", "CF"],
  ["Pontypridd", "Rhondda Cynon Taf", "Wales", "CF"],
  ["Aberystwyth", "Ceredigion", "Wales", "SY"],
  ["Bangor", "Gwynedd", "Wales", "LL"],
  ["Caernarfon", "Gwynedd", "Wales", "LL"],
  ["Llandudno", "Conwy", "Wales", "LL"],
  ["Rhyl", "Denbighshire", "Wales", "LL"],
  ["Colwyn Bay", "Conwy", "Wales", "LL"],
  ["Haverfordwest", "Pembrokeshire", "Wales", "SA"],
  ["Cwmbran", "Torfaen", "Wales", "NP"],
  ["Ebbw Vale", "Blaenau Gwent", "Wales", "NP"],
  ["Caerphilly", "Caerphilly", "Wales", "CF"],
  ["Mold", "Flintshire", "Wales", "CH"],

  // Scotland
  ["Dundee", "Dundee City", "Scotland", "DD"],
  ["Inverness", "Highland", "Scotland", "IV"],
  ["Perth", "Perth and Kinross", "Scotland", "PH"],
  ["Stirling", "Stirling", "Scotland", "FK"],
  ["Falkirk", "Falkirk", "Scotland", "FK"],
  ["Paisley", "Renfrewshire", "Scotland", "PA"],
  ["East Kilbride", "South Lanarkshire", "Scotland", "G"],
  ["Hamilton", "South Lanarkshire", "Scotland", "ML"],
  ["Motherwell", "North Lanarkshire", "Scotland", "ML"],
  ["Cumbernauld", "North Lanarkshire", "Scotland", "G"],
  ["Coatbridge", "North Lanarkshire", "Scotland", "ML"],
  ["Airdrie", "North Lanarkshire", "Scotland", "ML"],
  ["Kirkcaldy", "Fife", "Scotland", "KY"],
  ["Dunfermline", "Fife", "Scotland", "KY"],
  ["St Andrews", "Fife", "Scotland", "KY"],
  ["Livingston", "West Lothian", "Scotland", "EH"],
  ["Ayr", "South Ayrshire", "Scotland", "KA"],
  ["Kilmarnock", "East Ayrshire", "Scotland", "KA"],
  ["Greenock", "Inverclyde", "Scotland", "PA"],
  ["Dumfries", "Dumfries and Galloway", "Scotland", "DG"],
  ["Elgin", "Moray", "Scotland", "IV"],
  ["Oban", "Argyll and Bute", "Scotland", "PA"],
  ["Fort William", "Highland", "Scotland", "PH"],

  // Northern Ireland
  ["Londonderry", "County Londonderry", "Northern Ireland", "BT"],
  ["Lisburn", "County Antrim", "Northern Ireland", "BT"],
  ["Newtownabbey", "County Antrim", "Northern Ireland", "BT"],
  ["Bangor", "County Down", "Northern Ireland", "BT"],
  ["Newtownards", "County Down", "Northern Ireland", "BT"],
  ["Craigavon", "County Armagh", "Northern Ireland", "BT"],
  ["Ballymena", "County Antrim", "Northern Ireland", "BT"],
  ["Newry", "County Down", "Northern Ireland", "BT"],
  ["Coleraine", "County Londonderry", "Northern Ireland", "BT"],
  ["Omagh", "County Tyrone", "Northern Ireland", "BT"],
  ["Enniskillen", "County Fermanagh", "Northern Ireland", "BT"],
  ["Armagh", "County Armagh", "Northern Ireland", "BT"],
];
