/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SavedSearchesRouteImport } from './routes/saved-searches'
import { Route as ReferencingRouteImport } from './routes/referencing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ForLandlordsRouteImport } from './routes/for-landlords'
import { Route as ForAgentsRouteImport } from './routes/for-agents'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AreaGuidesRouteImport } from './routes/area-guides'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as AgenciesSlugRouteImport } from './routes/agencies.$slug'
import { Route as AuthenticatedWorkOrdersRouteImport } from './routes/_authenticated/work-orders'
import { Route as AuthenticatedViewingsRouteImport } from './routes/_authenticated/viewings'
import { Route as AuthenticatedVendorPortalRouteImport } from './routes/_authenticated/vendor-portal'
import { Route as AuthenticatedStatementsRouteImport } from './routes/_authenticated/statements'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedHmoRouteImport } from './routes/_authenticated/hmo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedAiCopyRouteImport } from './routes/_authenticated/ai-copy'
import { Route as AuthenticatedAgencyRouteImport } from './routes/_authenticated/agency'

const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSearchesRoute = SavedSearchesRouteImport.update({
  id: '/saved-searches',
  path: '/saved-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencingRoute = ReferencingRouteImport.update({
  id: '/referencing',
  path: '/referencing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLandlordsRoute = ForLandlordsRouteImport.update({
  id: '/for-landlords',
  path: '/for-landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgentsRoute = ForAgentsRouteImport.update({
  id: '/for-agents',
  path: '/for-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaGuidesRoute = AreaGuidesRouteImport.update({
  id: '/area-guides',
  path: '/area-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgenciesRoute,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AgenciesSlugRoute = AgenciesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgenciesRoute,
} as any)
const AuthenticatedWorkOrdersRoute = AuthenticatedWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViewingsRoute = AuthenticatedViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorPortalRoute =
  AuthenticatedVendorPortalRouteImport.update({
    id: '/vendor-portal',
    path: '/vendor-portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatementsRoute = AuthenticatedStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHmoRoute = AuthenticatedHmoRouteImport.update({
  id: '/hmo',
  path: '/hmo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiCopyRoute = AuthenticatedAiCopyRouteImport.update({
  id: '/ai-copy',
  path: '/ai-copy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgencyRoute = AuthenticatedAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRouteWithChildren
  '/area-guides': typeof AreaGuidesRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/complaints': typeof ComplaintsRoute
  '/cookies': typeof CookiesRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mortgage': typeof MortgageRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/referencing': typeof ReferencingRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/terms': typeof TermsRoute
  '/valuation': typeof ValuationRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/ai-copy': typeof AuthenticatedAiCopyRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hmo': typeof AuthenticatedHmoRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/vendor-portal': typeof AuthenticatedVendorPortalRoute
  '/viewings': typeof AuthenticatedViewingsRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-guides': typeof AreaGuidesRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/complaints': typeof ComplaintsRoute
  '/cookies': typeof CookiesRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/mortgage': typeof MortgageRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/referencing': typeof ReferencingRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/terms': typeof TermsRoute
  '/valuation': typeof ValuationRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/ai-copy': typeof AuthenticatedAiCopyRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hmo': typeof AuthenticatedHmoRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/vendor-portal': typeof AuthenticatedVendorPortalRoute
  '/viewings': typeof AuthenticatedViewingsRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/agencies': typeof AgenciesIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agencies': typeof AgenciesRouteWithChildren
  '/area-guides': typeof AreaGuidesRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/complaints': typeof ComplaintsRoute
  '/cookies': typeof CookiesRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mortgage': typeof MortgageRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/referencing': typeof ReferencingRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/terms': typeof TermsRoute
  '/valuation': typeof ValuationRoute
  '/_authenticated/agency': typeof AuthenticatedAgencyRoute
  '/_authenticated/ai-copy': typeof AuthenticatedAiCopyRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hmo': typeof AuthenticatedHmoRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statements': typeof AuthenticatedStatementsRoute
  '/_authenticated/vendor-portal': typeof AuthenticatedVendorPortalRoute
  '/_authenticated/viewings': typeof AuthenticatedViewingsRoute
  '/_authenticated/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencies'
    | '/area-guides'
    | '/auth'
    | '/business'
    | '/complaints'
    | '/cookies'
    | '/for-agents'
    | '/for-landlords'
    | '/marketplace'
    | '/mortgage'
    | '/platform'
    | '/privacy'
    | '/referencing'
    | '/saved-searches'
    | '/terms'
    | '/valuation'
    | '/agency'
    | '/ai-copy'
    | '/compliance'
    | '/contacts'
    | '/dashboard'
    | '/hmo'
    | '/inspections'
    | '/leads'
    | '/listings'
    | '/offers'
    | '/pipeline'
    | '/properties'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/statements'
    | '/vendor-portal'
    | '/viewings'
    | '/work-orders'
    | '/agencies/$slug'
    | '/marketplace/$slug'
    | '/modules/$slug'
    | '/agencies/'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/area-guides'
    | '/auth'
    | '/business'
    | '/complaints'
    | '/cookies'
    | '/for-agents'
    | '/for-landlords'
    | '/mortgage'
    | '/platform'
    | '/privacy'
    | '/referencing'
    | '/saved-searches'
    | '/terms'
    | '/valuation'
    | '/agency'
    | '/ai-copy'
    | '/compliance'
    | '/contacts'
    | '/dashboard'
    | '/hmo'
    | '/inspections'
    | '/leads'
    | '/listings'
    | '/offers'
    | '/pipeline'
    | '/properties'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/statements'
    | '/vendor-portal'
    | '/viewings'
    | '/work-orders'
    | '/agencies/$slug'
    | '/marketplace/$slug'
    | '/modules/$slug'
    | '/agencies'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agencies'
    | '/area-guides'
    | '/auth'
    | '/business'
    | '/complaints'
    | '/cookies'
    | '/for-agents'
    | '/for-landlords'
    | '/marketplace'
    | '/mortgage'
    | '/platform'
    | '/privacy'
    | '/referencing'
    | '/saved-searches'
    | '/terms'
    | '/valuation'
    | '/_authenticated/agency'
    | '/_authenticated/ai-copy'
    | '/_authenticated/compliance'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/hmo'
    | '/_authenticated/inspections'
    | '/_authenticated/leads'
    | '/_authenticated/listings'
    | '/_authenticated/offers'
    | '/_authenticated/pipeline'
    | '/_authenticated/properties'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/statements'
    | '/_authenticated/vendor-portal'
    | '/_authenticated/viewings'
    | '/_authenticated/work-orders'
    | '/agencies/$slug'
    | '/marketplace/$slug'
    | '/modules/$slug'
    | '/agencies/'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgenciesRoute: typeof AgenciesRouteWithChildren
  AreaGuidesRoute: typeof AreaGuidesRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  ComplaintsRoute: typeof ComplaintsRoute
  CookiesRoute: typeof CookiesRoute
  ForAgentsRoute: typeof ForAgentsRoute
  ForLandlordsRoute: typeof ForLandlordsRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MortgageRoute: typeof MortgageRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferencingRoute: typeof ReferencingRoute
  SavedSearchesRoute: typeof SavedSearchesRoute
  TermsRoute: typeof TermsRoute
  ValuationRoute: typeof ValuationRoute
  ModulesSlugRoute: typeof ModulesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-searches': {
      id: '/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof SavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencing': {
      id: '/referencing'
      path: '/referencing'
      fullPath: '/referencing'
      preLoaderRoute: typeof ReferencingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-landlords': {
      id: '/for-landlords'
      path: '/for-landlords'
      fullPath: '/for-landlords'
      preLoaderRoute: typeof ForLandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agents': {
      id: '/for-agents'
      path: '/for-agents'
      fullPath: '/for-agents'
      preLoaderRoute: typeof ForAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-guides': {
      id: '/area-guides'
      path: '/area-guides'
      fullPath: '/area-guides'
      preLoaderRoute: typeof AreaGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/agencies/$slug': {
      id: '/agencies/$slug'
      path: '/$slug'
      fullPath: '/agencies/$slug'
      preLoaderRoute: typeof AgenciesSlugRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/_authenticated/work-orders': {
      id: '/_authenticated/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof AuthenticatedWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viewings': {
      id: '/_authenticated/viewings'
      path: '/viewings'
      fullPath: '/viewings'
      preLoaderRoute: typeof AuthenticatedViewingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-portal': {
      id: '/_authenticated/vendor-portal'
      path: '/vendor-portal'
      fullPath: '/vendor-portal'
      preLoaderRoute: typeof AuthenticatedVendorPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statements': {
      id: '/_authenticated/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AuthenticatedStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hmo': {
      id: '/_authenticated/hmo'
      path: '/hmo'
      fullPath: '/hmo'
      preLoaderRoute: typeof AuthenticatedHmoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-copy': {
      id: '/_authenticated/ai-copy'
      path: '/ai-copy'
      fullPath: '/ai-copy'
      preLoaderRoute: typeof AuthenticatedAiCopyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agency': {
      id: '/_authenticated/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AuthenticatedAgencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgencyRoute: typeof AuthenticatedAgencyRoute
  AuthenticatedAiCopyRoute: typeof AuthenticatedAiCopyRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHmoRoute: typeof AuthenticatedHmoRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatementsRoute: typeof AuthenticatedStatementsRoute
  AuthenticatedVendorPortalRoute: typeof AuthenticatedVendorPortalRoute
  AuthenticatedViewingsRoute: typeof AuthenticatedViewingsRoute
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgencyRoute: AuthenticatedAgencyRoute,
  AuthenticatedAiCopyRoute: AuthenticatedAiCopyRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHmoRoute: AuthenticatedHmoRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatementsRoute: AuthenticatedStatementsRoute,
  AuthenticatedVendorPortalRoute: AuthenticatedVendorPortalRoute,
  AuthenticatedViewingsRoute: AuthenticatedViewingsRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AgenciesRouteChildren {
  AgenciesSlugRoute: typeof AgenciesSlugRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
}

const AgenciesRouteChildren: AgenciesRouteChildren = {
  AgenciesSlugRoute: AgenciesSlugRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
}

const AgenciesRouteWithChildren = AgenciesRoute._addFileChildren(
  AgenciesRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceSlugRoute: MarketplaceSlugRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgenciesRoute: AgenciesRouteWithChildren,
  AreaGuidesRoute: AreaGuidesRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  ComplaintsRoute: ComplaintsRoute,
  CookiesRoute: CookiesRoute,
  ForAgentsRoute: ForAgentsRoute,
  ForLandlordsRoute: ForLandlordsRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MortgageRoute: MortgageRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  ReferencingRoute: ReferencingRoute,
  SavedSearchesRoute: SavedSearchesRoute,
  TermsRoute: TermsRoute,
  ValuationRoute: ValuationRoute,
  ModulesSlugRoute: ModulesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
