/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ForLandlordsRouteImport } from './routes/for-landlords'
import { Route as ForAgentsRouteImport } from './routes/for-agents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as AgenciesSlugRouteImport } from './routes/agencies.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedAgencyRouteImport } from './routes/_authenticated/agency'

const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLandlordsRoute = ForLandlordsRouteImport.update({
  id: '/for-landlords',
  path: '/for-landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgentsRoute = ForAgentsRouteImport.update({
  id: '/for-agents',
  path: '/for-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgenciesRoute,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AgenciesSlugRoute = AgenciesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgenciesRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgencyRoute = AuthenticatedAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRouteWithChildren
  '/auth': typeof AuthRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/agency': typeof AuthenticatedAgencyRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/agencies': typeof AgenciesIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agencies': typeof AgenciesRouteWithChildren
  '/auth': typeof AuthRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/_authenticated/agency': typeof AuthenticatedAgencyRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencies'
    | '/auth'
    | '/for-agents'
    | '/for-landlords'
    | '/marketplace'
    | '/agency'
    | '/compliance'
    | '/dashboard'
    | '/leads'
    | '/listings'
    | '/pipeline'
    | '/properties'
    | '/settings'
    | '/agencies/$slug'
    | '/marketplace/$slug'
    | '/agencies/'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/for-agents'
    | '/for-landlords'
    | '/agency'
    | '/compliance'
    | '/dashboard'
    | '/leads'
    | '/listings'
    | '/pipeline'
    | '/properties'
    | '/settings'
    | '/agencies/$slug'
    | '/marketplace/$slug'
    | '/agencies'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agencies'
    | '/auth'
    | '/for-agents'
    | '/for-landlords'
    | '/marketplace'
    | '/_authenticated/agency'
    | '/_authenticated/compliance'
    | '/_authenticated/dashboard'
    | '/_authenticated/leads'
    | '/_authenticated/listings'
    | '/_authenticated/pipeline'
    | '/_authenticated/properties'
    | '/_authenticated/settings'
    | '/agencies/$slug'
    | '/marketplace/$slug'
    | '/agencies/'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgenciesRoute: typeof AgenciesRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForAgentsRoute: typeof ForAgentsRoute
  ForLandlordsRoute: typeof ForLandlordsRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-landlords': {
      id: '/for-landlords'
      path: '/for-landlords'
      fullPath: '/for-landlords'
      preLoaderRoute: typeof ForLandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agents': {
      id: '/for-agents'
      path: '/for-agents'
      fullPath: '/for-agents'
      preLoaderRoute: typeof ForAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/agencies/$slug': {
      id: '/agencies/$slug'
      path: '/$slug'
      fullPath: '/agencies/$slug'
      preLoaderRoute: typeof AgenciesSlugRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agency': {
      id: '/_authenticated/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AuthenticatedAgencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgencyRoute: typeof AuthenticatedAgencyRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgencyRoute: AuthenticatedAgencyRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AgenciesRouteChildren {
  AgenciesSlugRoute: typeof AgenciesSlugRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
}

const AgenciesRouteChildren: AgenciesRouteChildren = {
  AgenciesSlugRoute: AgenciesSlugRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
}

const AgenciesRouteWithChildren = AgenciesRoute._addFileChildren(
  AgenciesRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceSlugRoute: MarketplaceSlugRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgenciesRoute: AgenciesRouteWithChildren,
  AuthRoute: AuthRoute,
  ForAgentsRoute: ForAgentsRoute,
  ForLandlordsRoute: ForLandlordsRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
