/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SavedSearchesRouteImport } from './routes/saved-searches'
import { Route as ReferencingRouteImport } from './routes/referencing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ForLandlordsRouteImport } from './routes/for-landlords'
import { Route as ForAgentsRouteImport } from './routes/for-agents'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AreaGuidesRouteImport } from './routes/area-guides'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AgenciesIndexRouteImport } from './routes/agencies.index'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AgenciesSlugRouteImport } from './routes/agencies.$slug'
import { Route as AuthenticatedWorkOrdersRouteImport } from './routes/_authenticated/work-orders'
import { Route as AuthenticatedViewingsRouteImport } from './routes/_authenticated/viewings'
import { Route as AuthenticatedVendorPortalRouteImport } from './routes/_authenticated/vendor-portal'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedStatementsRouteImport } from './routes/_authenticated/statements'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedRightToRentRouteImport } from './routes/_authenticated/right-to-rent'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRenewalsRouteImport } from './routes/_authenticated/renewals'
import { Route as AuthenticatedReferencingCasesRouteImport } from './routes/_authenticated.referencing-cases'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedMoveRouteImport } from './routes/_authenticated/move'
import { Route as AuthenticatedMobileInspectionRouteImport } from './routes/_authenticated/mobile-inspection'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedLeaseholdRouteImport } from './routes/_authenticated/leasehold'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedHmoRouteImport } from './routes/_authenticated/hmo'
import { Route as AuthenticatedEvidenceRouteImport } from './routes/_authenticated/evidence'
import { Route as AuthenticatedESignRouteImport } from './routes/_authenticated/e-sign'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDepositsRouteImport } from './routes/_authenticated/deposits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractorMarketplaceRouteImport } from './routes/_authenticated/contractor-marketplace'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedCommercialRouteImport } from './routes/_authenticated/commercial'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedArrearsRouteImport } from './routes/_authenticated/arrears'
import { Route as AuthenticatedAiCopyRouteImport } from './routes/_authenticated/ai-copy'
import { Route as AuthenticatedAgencyRouteImport } from './routes/_authenticated/agency'
import { Route as ApiPublicReferencingWebhookRouteImport } from './routes/api/public/referencing-webhook'
import { Route as ApiPublicHooksMatchSavedSearchesRouteImport } from './routes/api/public/hooks/match-saved-searches'

const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSearchesRoute = SavedSearchesRouteImport.update({
  id: '/saved-searches',
  path: '/saved-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencingRoute = ReferencingRouteImport.update({
  id: '/referencing',
  path: '/referencing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForLandlordsRoute = ForLandlordsRouteImport.update({
  id: '/for-landlords',
  path: '/for-landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgentsRoute = ForAgentsRouteImport.update({
  id: '/for-agents',
  path: '/for-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaGuidesRoute = AreaGuidesRouteImport.update({
  id: '/area-guides',
  path: '/area-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgenciesRoute,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesSlugRoute = AgenciesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgenciesRoute,
} as any)
const AuthenticatedWorkOrdersRoute = AuthenticatedWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViewingsRoute = AuthenticatedViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorPortalRoute =
  AuthenticatedVendorPortalRouteImport.update({
    id: '/vendor-portal',
    path: '/vendor-portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatementsRoute = AuthenticatedStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRightToRentRoute =
  AuthenticatedRightToRentRouteImport.update({
    id: '/right-to-rent',
    path: '/right-to-rent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenewalsRoute = AuthenticatedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferencingCasesRoute =
  AuthenticatedReferencingCasesRouteImport.update({
    id: '/referencing-cases',
    path: '/referencing-cases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoveRoute = AuthenticatedMoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMobileInspectionRoute =
  AuthenticatedMobileInspectionRouteImport.update({
    id: '/mobile-inspection',
    path: '/mobile-inspection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaseholdRoute = AuthenticatedLeaseholdRouteImport.update({
  id: '/leasehold',
  path: '/leasehold',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHmoRoute = AuthenticatedHmoRouteImport.update({
  id: '/hmo',
  path: '/hmo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvidenceRoute = AuthenticatedEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedESignRoute = AuthenticatedESignRouteImport.update({
  id: '/e-sign',
  path: '/e-sign',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositsRoute = AuthenticatedDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractorMarketplaceRoute =
  AuthenticatedContractorMarketplaceRouteImport.update({
    id: '/contractor-marketplace',
    path: '/contractor-marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommercialRoute = AuthenticatedCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArrearsRoute = AuthenticatedArrearsRouteImport.update({
  id: '/arrears',
  path: '/arrears',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiCopyRoute = AuthenticatedAiCopyRouteImport.update({
  id: '/ai-copy',
  path: '/ai-copy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgencyRoute = AuthenticatedAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicReferencingWebhookRoute =
  ApiPublicReferencingWebhookRouteImport.update({
    id: '/api/public/referencing-webhook',
    path: '/api/public/referencing-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMatchSavedSearchesRoute =
  ApiPublicHooksMatchSavedSearchesRouteImport.update({
    id: '/api/public/hooks/match-saved-searches',
    path: '/api/public/hooks/match-saved-searches',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRouteWithChildren
  '/area-guides': typeof AreaGuidesRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/complaints': typeof ComplaintsRoute
  '/cookies': typeof CookiesRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mortgage': typeof MortgageRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/referencing': typeof ReferencingRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/terms': typeof TermsRoute
  '/valuation': typeof ValuationRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/ai-copy': typeof AuthenticatedAiCopyRoute
  '/arrears': typeof AuthenticatedArrearsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/commercial': typeof AuthenticatedCommercialRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/contractor-marketplace': typeof AuthenticatedContractorMarketplaceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposits': typeof AuthenticatedDepositsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/e-sign': typeof AuthenticatedESignRoute
  '/evidence': typeof AuthenticatedEvidenceRoute
  '/hmo': typeof AuthenticatedHmoRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/leasehold': typeof AuthenticatedLeaseholdRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/mobile-inspection': typeof AuthenticatedMobileInspectionRoute
  '/move': typeof AuthenticatedMoveRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/referencing-cases': typeof AuthenticatedReferencingCasesRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/right-to-rent': typeof AuthenticatedRightToRentRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/vendor-portal': typeof AuthenticatedVendorPortalRoute
  '/viewings': typeof AuthenticatedViewingsRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/public/referencing-webhook': typeof ApiPublicReferencingWebhookRoute
  '/api/public/hooks/match-saved-searches': typeof ApiPublicHooksMatchSavedSearchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-guides': typeof AreaGuidesRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/complaints': typeof ComplaintsRoute
  '/cookies': typeof CookiesRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/mortgage': typeof MortgageRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/referencing': typeof ReferencingRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/terms': typeof TermsRoute
  '/valuation': typeof ValuationRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/ai-copy': typeof AuthenticatedAiCopyRoute
  '/arrears': typeof AuthenticatedArrearsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/commercial': typeof AuthenticatedCommercialRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/contractor-marketplace': typeof AuthenticatedContractorMarketplaceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposits': typeof AuthenticatedDepositsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/e-sign': typeof AuthenticatedESignRoute
  '/evidence': typeof AuthenticatedEvidenceRoute
  '/hmo': typeof AuthenticatedHmoRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/leasehold': typeof AuthenticatedLeaseholdRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/mobile-inspection': typeof AuthenticatedMobileInspectionRoute
  '/move': typeof AuthenticatedMoveRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/referencing-cases': typeof AuthenticatedReferencingCasesRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/right-to-rent': typeof AuthenticatedRightToRentRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/vendor-portal': typeof AuthenticatedVendorPortalRoute
  '/viewings': typeof AuthenticatedViewingsRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/agencies': typeof AgenciesIndexRoute
  '/blog': typeof BlogIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/api/public/referencing-webhook': typeof ApiPublicReferencingWebhookRoute
  '/api/public/hooks/match-saved-searches': typeof ApiPublicHooksMatchSavedSearchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agencies': typeof AgenciesRouteWithChildren
  '/area-guides': typeof AreaGuidesRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/complaints': typeof ComplaintsRoute
  '/cookies': typeof CookiesRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-landlords': typeof ForLandlordsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/mortgage': typeof MortgageRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/referencing': typeof ReferencingRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/terms': typeof TermsRoute
  '/valuation': typeof ValuationRoute
  '/_authenticated/agency': typeof AuthenticatedAgencyRoute
  '/_authenticated/ai-copy': typeof AuthenticatedAiCopyRoute
  '/_authenticated/arrears': typeof AuthenticatedArrearsRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/commercial': typeof AuthenticatedCommercialRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/contractor-marketplace': typeof AuthenticatedContractorMarketplaceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposits': typeof AuthenticatedDepositsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/e-sign': typeof AuthenticatedESignRoute
  '/_authenticated/evidence': typeof AuthenticatedEvidenceRoute
  '/_authenticated/hmo': typeof AuthenticatedHmoRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/leasehold': typeof AuthenticatedLeaseholdRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/mobile-inspection': typeof AuthenticatedMobileInspectionRoute
  '/_authenticated/move': typeof AuthenticatedMoveRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/referencing-cases': typeof AuthenticatedReferencingCasesRoute
  '/_authenticated/renewals': typeof AuthenticatedRenewalsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/right-to-rent': typeof AuthenticatedRightToRentRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statements': typeof AuthenticatedStatementsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/vendor-portal': typeof AuthenticatedVendorPortalRoute
  '/_authenticated/viewings': typeof AuthenticatedViewingsRoute
  '/_authenticated/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/agencies/$slug': typeof AgenciesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/public/referencing-webhook': typeof ApiPublicReferencingWebhookRoute
  '/api/public/hooks/match-saved-searches': typeof ApiPublicHooksMatchSavedSearchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencies'
    | '/area-guides'
    | '/auth'
    | '/business'
    | '/complaints'
    | '/cookies'
    | '/for-agents'
    | '/for-landlords'
    | '/marketplace'
    | '/mortgage'
    | '/platform'
    | '/privacy'
    | '/referencing'
    | '/saved-searches'
    | '/terms'
    | '/valuation'
    | '/agency'
    | '/ai-copy'
    | '/arrears'
    | '/branches'
    | '/commercial'
    | '/compliance'
    | '/contacts'
    | '/contractor-marketplace'
    | '/dashboard'
    | '/deposits'
    | '/documents'
    | '/e-sign'
    | '/evidence'
    | '/hmo'
    | '/inspections'
    | '/leads'
    | '/leasehold'
    | '/listings'
    | '/media'
    | '/mobile-inspection'
    | '/move'
    | '/offers'
    | '/pipeline'
    | '/properties'
    | '/referencing-cases'
    | '/renewals'
    | '/reports'
    | '/right-to-rent'
    | '/sales'
    | '/settings'
    | '/statements'
    | '/templates'
    | '/vendor-portal'
    | '/viewings'
    | '/work-orders'
    | '/agencies/$slug'
    | '/blog/$slug'
    | '/marketplace/$slug'
    | '/modules/$slug'
    | '/agencies/'
    | '/blog/'
    | '/marketplace/'
    | '/api/public/referencing-webhook'
    | '/api/public/hooks/match-saved-searches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/area-guides'
    | '/auth'
    | '/business'
    | '/complaints'
    | '/cookies'
    | '/for-agents'
    | '/for-landlords'
    | '/mortgage'
    | '/platform'
    | '/privacy'
    | '/referencing'
    | '/saved-searches'
    | '/terms'
    | '/valuation'
    | '/agency'
    | '/ai-copy'
    | '/arrears'
    | '/branches'
    | '/commercial'
    | '/compliance'
    | '/contacts'
    | '/contractor-marketplace'
    | '/dashboard'
    | '/deposits'
    | '/documents'
    | '/e-sign'
    | '/evidence'
    | '/hmo'
    | '/inspections'
    | '/leads'
    | '/leasehold'
    | '/listings'
    | '/media'
    | '/mobile-inspection'
    | '/move'
    | '/offers'
    | '/pipeline'
    | '/properties'
    | '/referencing-cases'
    | '/renewals'
    | '/reports'
    | '/right-to-rent'
    | '/sales'
    | '/settings'
    | '/statements'
    | '/templates'
    | '/vendor-portal'
    | '/viewings'
    | '/work-orders'
    | '/agencies/$slug'
    | '/blog/$slug'
    | '/marketplace/$slug'
    | '/modules/$slug'
    | '/agencies'
    | '/blog'
    | '/marketplace'
    | '/api/public/referencing-webhook'
    | '/api/public/hooks/match-saved-searches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agencies'
    | '/area-guides'
    | '/auth'
    | '/business'
    | '/complaints'
    | '/cookies'
    | '/for-agents'
    | '/for-landlords'
    | '/marketplace'
    | '/mortgage'
    | '/platform'
    | '/privacy'
    | '/referencing'
    | '/saved-searches'
    | '/terms'
    | '/valuation'
    | '/_authenticated/agency'
    | '/_authenticated/ai-copy'
    | '/_authenticated/arrears'
    | '/_authenticated/branches'
    | '/_authenticated/commercial'
    | '/_authenticated/compliance'
    | '/_authenticated/contacts'
    | '/_authenticated/contractor-marketplace'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposits'
    | '/_authenticated/documents'
    | '/_authenticated/e-sign'
    | '/_authenticated/evidence'
    | '/_authenticated/hmo'
    | '/_authenticated/inspections'
    | '/_authenticated/leads'
    | '/_authenticated/leasehold'
    | '/_authenticated/listings'
    | '/_authenticated/media'
    | '/_authenticated/mobile-inspection'
    | '/_authenticated/move'
    | '/_authenticated/offers'
    | '/_authenticated/pipeline'
    | '/_authenticated/properties'
    | '/_authenticated/referencing-cases'
    | '/_authenticated/renewals'
    | '/_authenticated/reports'
    | '/_authenticated/right-to-rent'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/statements'
    | '/_authenticated/templates'
    | '/_authenticated/vendor-portal'
    | '/_authenticated/viewings'
    | '/_authenticated/work-orders'
    | '/agencies/$slug'
    | '/blog/$slug'
    | '/marketplace/$slug'
    | '/modules/$slug'
    | '/agencies/'
    | '/blog/'
    | '/marketplace/'
    | '/api/public/referencing-webhook'
    | '/api/public/hooks/match-saved-searches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgenciesRoute: typeof AgenciesRouteWithChildren
  AreaGuidesRoute: typeof AreaGuidesRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  ComplaintsRoute: typeof ComplaintsRoute
  CookiesRoute: typeof CookiesRoute
  ForAgentsRoute: typeof ForAgentsRoute
  ForLandlordsRoute: typeof ForLandlordsRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MortgageRoute: typeof MortgageRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferencingRoute: typeof ReferencingRoute
  SavedSearchesRoute: typeof SavedSearchesRoute
  TermsRoute: typeof TermsRoute
  ValuationRoute: typeof ValuationRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ModulesSlugRoute: typeof ModulesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicReferencingWebhookRoute: typeof ApiPublicReferencingWebhookRoute
  ApiPublicHooksMatchSavedSearchesRoute: typeof ApiPublicHooksMatchSavedSearchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-searches': {
      id: '/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof SavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencing': {
      id: '/referencing'
      path: '/referencing'
      fullPath: '/referencing'
      preLoaderRoute: typeof ReferencingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-landlords': {
      id: '/for-landlords'
      path: '/for-landlords'
      fullPath: '/for-landlords'
      preLoaderRoute: typeof ForLandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agents': {
      id: '/for-agents'
      path: '/for-agents'
      fullPath: '/for-agents'
      preLoaderRoute: typeof ForAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-guides': {
      id: '/area-guides'
      path: '/area-guides'
      fullPath: '/area-guides'
      preLoaderRoute: typeof AreaGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/$slug': {
      id: '/agencies/$slug'
      path: '/$slug'
      fullPath: '/agencies/$slug'
      preLoaderRoute: typeof AgenciesSlugRouteImport
      parentRoute: typeof AgenciesRoute
    }
    '/_authenticated/work-orders': {
      id: '/_authenticated/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof AuthenticatedWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viewings': {
      id: '/_authenticated/viewings'
      path: '/viewings'
      fullPath: '/viewings'
      preLoaderRoute: typeof AuthenticatedViewingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor-portal': {
      id: '/_authenticated/vendor-portal'
      path: '/vendor-portal'
      fullPath: '/vendor-portal'
      preLoaderRoute: typeof AuthenticatedVendorPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statements': {
      id: '/_authenticated/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AuthenticatedStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/right-to-rent': {
      id: '/_authenticated/right-to-rent'
      path: '/right-to-rent'
      fullPath: '/right-to-rent'
      preLoaderRoute: typeof AuthenticatedRightToRentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renewals': {
      id: '/_authenticated/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthenticatedRenewalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referencing-cases': {
      id: '/_authenticated/referencing-cases'
      path: '/referencing-cases'
      fullPath: '/referencing-cases'
      preLoaderRoute: typeof AuthenticatedReferencingCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/move': {
      id: '/_authenticated/move'
      path: '/move'
      fullPath: '/move'
      preLoaderRoute: typeof AuthenticatedMoveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile-inspection': {
      id: '/_authenticated/mobile-inspection'
      path: '/mobile-inspection'
      fullPath: '/mobile-inspection'
      preLoaderRoute: typeof AuthenticatedMobileInspectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leasehold': {
      id: '/_authenticated/leasehold'
      path: '/leasehold'
      fullPath: '/leasehold'
      preLoaderRoute: typeof AuthenticatedLeaseholdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hmo': {
      id: '/_authenticated/hmo'
      path: '/hmo'
      fullPath: '/hmo'
      preLoaderRoute: typeof AuthenticatedHmoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evidence': {
      id: '/_authenticated/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AuthenticatedEvidenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/e-sign': {
      id: '/_authenticated/e-sign'
      path: '/e-sign'
      fullPath: '/e-sign'
      preLoaderRoute: typeof AuthenticatedESignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposits': {
      id: '/_authenticated/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AuthenticatedDepositsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contractor-marketplace': {
      id: '/_authenticated/contractor-marketplace'
      path: '/contractor-marketplace'
      fullPath: '/contractor-marketplace'
      preLoaderRoute: typeof AuthenticatedContractorMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial': {
      id: '/_authenticated/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof AuthenticatedCommercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arrears': {
      id: '/_authenticated/arrears'
      path: '/arrears'
      fullPath: '/arrears'
      preLoaderRoute: typeof AuthenticatedArrearsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-copy': {
      id: '/_authenticated/ai-copy'
      path: '/ai-copy'
      fullPath: '/ai-copy'
      preLoaderRoute: typeof AuthenticatedAiCopyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agency': {
      id: '/_authenticated/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AuthenticatedAgencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/referencing-webhook': {
      id: '/api/public/referencing-webhook'
      path: '/api/public/referencing-webhook'
      fullPath: '/api/public/referencing-webhook'
      preLoaderRoute: typeof ApiPublicReferencingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/match-saved-searches': {
      id: '/api/public/hooks/match-saved-searches'
      path: '/api/public/hooks/match-saved-searches'
      fullPath: '/api/public/hooks/match-saved-searches'
      preLoaderRoute: typeof ApiPublicHooksMatchSavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgencyRoute: typeof AuthenticatedAgencyRoute
  AuthenticatedAiCopyRoute: typeof AuthenticatedAiCopyRoute
  AuthenticatedArrearsRoute: typeof AuthenticatedArrearsRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCommercialRoute: typeof AuthenticatedCommercialRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedContractorMarketplaceRoute: typeof AuthenticatedContractorMarketplaceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositsRoute: typeof AuthenticatedDepositsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedESignRoute: typeof AuthenticatedESignRoute
  AuthenticatedEvidenceRoute: typeof AuthenticatedEvidenceRoute
  AuthenticatedHmoRoute: typeof AuthenticatedHmoRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLeaseholdRoute: typeof AuthenticatedLeaseholdRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedMobileInspectionRoute: typeof AuthenticatedMobileInspectionRoute
  AuthenticatedMoveRoute: typeof AuthenticatedMoveRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedReferencingCasesRoute: typeof AuthenticatedReferencingCasesRoute
  AuthenticatedRenewalsRoute: typeof AuthenticatedRenewalsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRightToRentRoute: typeof AuthenticatedRightToRentRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatementsRoute: typeof AuthenticatedStatementsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedVendorPortalRoute: typeof AuthenticatedVendorPortalRoute
  AuthenticatedViewingsRoute: typeof AuthenticatedViewingsRoute
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgencyRoute: AuthenticatedAgencyRoute,
  AuthenticatedAiCopyRoute: AuthenticatedAiCopyRoute,
  AuthenticatedArrearsRoute: AuthenticatedArrearsRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCommercialRoute: AuthenticatedCommercialRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedContractorMarketplaceRoute:
    AuthenticatedContractorMarketplaceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositsRoute: AuthenticatedDepositsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedESignRoute: AuthenticatedESignRoute,
  AuthenticatedEvidenceRoute: AuthenticatedEvidenceRoute,
  AuthenticatedHmoRoute: AuthenticatedHmoRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLeaseholdRoute: AuthenticatedLeaseholdRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedMobileInspectionRoute: AuthenticatedMobileInspectionRoute,
  AuthenticatedMoveRoute: AuthenticatedMoveRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedReferencingCasesRoute: AuthenticatedReferencingCasesRoute,
  AuthenticatedRenewalsRoute: AuthenticatedRenewalsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRightToRentRoute: AuthenticatedRightToRentRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatementsRoute: AuthenticatedStatementsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedVendorPortalRoute: AuthenticatedVendorPortalRoute,
  AuthenticatedViewingsRoute: AuthenticatedViewingsRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AgenciesRouteChildren {
  AgenciesSlugRoute: typeof AgenciesSlugRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
}

const AgenciesRouteChildren: AgenciesRouteChildren = {
  AgenciesSlugRoute: AgenciesSlugRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
}

const AgenciesRouteWithChildren = AgenciesRoute._addFileChildren(
  AgenciesRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceSlugRoute: MarketplaceSlugRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgenciesRoute: AgenciesRouteWithChildren,
  AreaGuidesRoute: AreaGuidesRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  ComplaintsRoute: ComplaintsRoute,
  CookiesRoute: CookiesRoute,
  ForAgentsRoute: ForAgentsRoute,
  ForLandlordsRoute: ForLandlordsRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MortgageRoute: MortgageRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  ReferencingRoute: ReferencingRoute,
  SavedSearchesRoute: SavedSearchesRoute,
  TermsRoute: TermsRoute,
  ValuationRoute: ValuationRoute,
  BlogSlugRoute: BlogSlugRoute,
  ModulesSlugRoute: ModulesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicReferencingWebhookRoute: ApiPublicReferencingWebhookRoute,
  ApiPublicHooksMatchSavedSearchesRoute: ApiPublicHooksMatchSavedSearchesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
